In [1]:
from qutip import *

In [2]:
ket = (basis(5, 0) + basis(5, 1)).unit()

In [3]:
n = num(5)

In [6]:
print((n*ket))

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]


$$n=\begin{pmatrix}
0 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 2 & 0\\
0 & 0 & 0 & 3

\end{pmatrix}$$

$$
\ket{\psi} = 
\begin{pmatrix}
1\\
1\\
0\\
0
\end{pmatrix}
$$

$$
n\ket{\psi} = \begin{pmatrix}
0 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 2 & 0\\
0 & 0 & 0 & 3

\end{pmatrix}
\begin{pmatrix}
1\\
1\\
0\\
0
\end{pmatrix}
$$

In [9]:
import numpy as np

vac = basis(5, 0)

d = displace(5, 1j)

s = squeeze(5, np.complex(0.25, 0.25))

print(vac)
print(d)

print(d * vac)
print(s * vac)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[ 0.60655682+0.j          0.        +0.60628133j -0.4303874 +0.j
   0.        -0.24104351j  0.14552147+0.j        ]
 [ 0.        +0.60628133j -0.00210288+0.j          0.        +0.43991167j
  -0.45440991+0.j          0.        -0.48208701j]
 [-0.4303874 +0.j          0.        +0.43991167j -0.25430923+0.j
   0.        +0.02744907j -0.74553187+0.j        ]
 [ 0.        -0.24104351j -0.45440991+0.j          0.        +0.02744907j
  -0.74415115+0.j          0.        +0.42531786j]
 [ 0.14552147+0.j          0.        -0.48208701j -0.74553187+0.j
   0.        +0.42531786j -0.09850161+0.j        ]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.60655682+0.j        ]
 [ 0.        +0.60628133j]
 [-0.4303874 +0.j        ]
 [ 0.        -0.24104351j]
 [ 0.14552147+0.j   

C:\Users\s5027305\AppData\Local\Temp\ipykernel_8392\381209609.py:7: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s = squeeze(5, np.complex(0.25, 0.25))


In [23]:
print(sigmap())

spin = basis(2, 1)
print(spin)
print(sigmap() * spin)

spin2 = basis(2, 0)

print(sigmam())
print(sigmam() * spin2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 1.]
 [0. 0.]]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]


In [26]:
spin1 = basis(2, 0)

spin2 = basis(2, 1)

two_spins = tensor(spin1, spin2)

sz1 = tensor(sigmaz(), qeye(2))

sz2 = tensor(qeye(2), sigmaz())

np.testing.assert_almost_equal(expect(sz1, two_spins), 1)

np.testing.assert_almost_equal(expect(sz2, two_spins), -1)

$$
\ket{\Psi} = \ket{\psi_1} \otimes \ket{\psi_2}
$$